config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :tools do
    resources :comments
  end

  resources :analytics do
    resources :events
  end

end

app/models/analytic.rb
class Analytic < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 4}
  validates :date1, presence: true, length: {is: 10}
  validates :date2, presence: true, length: {is: 10}
  validates :android_key, presence: true, length: {is: 20}
  validates :iphone_key, presence: true, length: {is: 20}
  validates :ipad_key, presence: true, length: {is: 20}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tool
  validates :commenter, presence: true, length: {minimum: 4}
  validates :body, presence: true, length: {minimum: 4}
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 4}
  
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  require './meg_flurry_analytics'
  attr_reader :analytic

  def new
    @analytic = Analytic.new
  end

  def create
    @analytic = Analytic.new(analytic_params)
    if @analytic.nil?
      puts "Analyse konnte nicht erstellt werden"
    else
      #Funktion analyse
      getAnalyticPara
    end

    if @analytic.save

      redirect_to @analytic

    else
      render 'new'
    end
  end

  def index
    @analytic = Analytic.all
  end


  def edit
    @analytic = Analytic.find(params[:id])
  end

  def update
    @analytic = Analytic.find(params[:id])

    if @analytic.update(analytic_params)
      redirect_to @analytic
    else
      render 'edit'
    end
  end

  def show
    @analytic = Analytic.find(params[:id])

  end

  def destroy

    @analytic = Analytic.find(params[:id])
    @analytic.destroy

    redirect_to analytics_path
  end



  private

  def analytic_params
    params.require(:analytic).permit(:title,:date1,:date2,:android_key,:iphone_key,:ipad_key)
  end

  #führt die eigentliche Analysefunktion aus, die Daten der Drittanbieter besorgt
  def getAnalyticPara

    options = {
        "flurry_iphone_api_key"  => @analytic.iphone_key,
        "flurry_ipad_api_key"    => @analytic.ipad_key,
        "flurry_android_api_key" =>  @analytic.ipad_key
    }

    @para = MegFlurryAnalytics.new(options)

    @analytic.iPhoneUser = @para.iphone(from=@analytic.date1, to=@analytic.date2)
    @analytic.iPadUser = @para.ipad(from=@analytic.date1, to=@analytic.date2)
    @analytic.androidUser = @para.android(from=@analytic.date1, to=@analytic.date2)

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret",only: :destroy

  def create
    @tool = Tool.find(params[:tool_id])
    @comment = @tool.comments.create(comment_params)
    redirect_to tool_path(@tool)
  end

  def destroy
    @tool = Tool.find(params[:tool_id])
    @comment = @tool.comments.find(params[:id])
    @comment.destroy
    redirect_to tool_path(@tool)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def new
    @tool = Tool.new
  end
  
  def create
    @tool = Tool.new(tool_params)
    
    if @tool.save
      redirect_to @tool
    else
      render 'new'
    end
    
  end
  
  def index
    @tools =Tool.all
  end
  
  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])

    if @tool.update(tool_params)
      redirect_to @tool
    else
      render 'edit'
    end
  end
  
  def show
    @tool = Tool.find(params[:id])
    #@tool = Tool.all
  end
  
  def destroy

    @tool = Tool.find(params[:id])
    @tool.destroy

    redirect_to tools_path
  end
  
  private
    def tool_params
      params.require(:tool).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper



end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/analytics/_form.erb
<%= form_for @analytic do |f| %>
    <% if @analytic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@analytic.errors.count, "error") %>Analyse konnte nicht durchgeführt
            werden aus folgenden Gründen:</h2>
          <ul><% @analytic.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %></ul>
        </div>
    <% end %>


    <table>
      <tr>
        <th><p>Geben sie das zu analysierende Event, den Zeitraum der Erfassung und die entsprechenden ApiKeys ein.</p></th>
      </tr>
    </table>
    <table>
    <tr>

            <td><p>

              <%= f.label :Eventname %><br>

              <%= f.text_field :title %>
            </p>
          </td>
          </tr>

          <tr>
            <td><p>
                <%= f.label :Startdatum %> (YYYY-MM-DD)<br>
                <%= f.text_field :date1 %><br>
            </p>
            </td>
            <td><p>
                <%= f.label :Enddatum %> (YYYY-MM-DD)<br>
                <%= f.text_field :date2 %><br>
            </p>
            </td>
          </tr>

            <tr>
            <td><p>
              <%= f.label :AndroidKey %> (20 Stellig)<br>
              <%= f.text_field :android_key %><br>
            </p>
            </td>
            <td><p>
              <%= f.label :IphoneKey %> (20 Stellig)<br>
              <%= f.text_field :iphone_key %><br>
            </p>
            </td>
            <td><p>
              <%= f.label :IpadKey %> (20 Stellig)<br>
              <%= f.text_field :ipad_key %><br>
            </p>
            </td>
          </tr>
    </table>

    <p>
      <br>
      <%= f.submit %>
      <br>
      <br>
    </p>



<% end %>

app/views/analytics/index.html.erb
<h1>Alle Analysen im Überblick</h1>

<p><%= link_to 'Neue Analyse', new_analytic_path %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <!-- <th>Text</th> -->
  </tr>

  <% @analytic.each do |analytic| %>
      <tr >
        <td><%= analytic.title %></td>
        <td><%= analytic.date1 %></td>
        <td><%= analytic.date2 %></td>
        <td><%= link_to 'Zeigen', analytic_path(analytic) %></td>
        <td><%= link_to 'Bearbeiten', edit_analytic_path(analytic) %></td>
        <td><%= link_to 'Löschen', analytic_path(analytic),
                        method: :delete, data: { confirm: 'Bist du sicher?' } %></td>
      </tr>
  <% end %>
</table>

<p><%= link_to 'Startseite', controller: 'welcome' %></p>

app/views/analytics/new.erb
<h1>Analyse eines Events</h1>
<p> Hier können Events analysiert werden</p>
<br>
<br>
<p>
  <%= render "analytics/form" %>
</p>

<p><%= link_to 'Startseite', controller: 'welcome' %></p>

app/views/analytics/show.erb
<h1>Analyse des Events <%= @analytic.title %>  im Zeitraum vom <%= @analytic.date1 %> bis zum <%= @analytic.date2 %></h1>


<table>

  <tr>
    <th>Nutzer/Downloads</th>
  </tr>
</table>

<table style="border-style: dashed">
  <tr>
    <th>IPhone</th>
    <th>IPad</th>
    <th>Android</th>
    <th>Mobile Website</th>
  </tr>

  <tr>

    <td>  <%= @analytic.iPhoneUser %>  </td>
    <td>  <%= @analytic.iPadUser %>  </td>
    <td>  <%= @analytic.androidUser %>  </td>
    <td>    <%= @analytic.mwUser %>  </td>
  </tr>

  <tr>
    <td>Gesamt: </td>
  </tr>
</table>

<br>
<br>
<%= link_to 'Zurück', analytics_path %>
| <%= link_to 'Startseite', controller: 'welcome' %>

app/views/comments/_comment.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Kommentar löschen', [comment.tool, comment],
              method: :delete,
              data: { confirm: 'Sind sie sicher?' } %>
</p>

app/views/comments/_form.erb
<%= form_for([@tool, @tool.comments.build]) do |f| %>



    <p>
      <%= f.label :Ersteller %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :Text %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/index/index.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>analytics in columns</title>

		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<style type="text/css">
${demo.css}
		</style>
		<script type="text/javascript">
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: [
                'Downloads',
                'Sessions'
            ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'entities'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'iPhone',
            data: [<%=@dnloads_iPhone%>, <%=@sessions_iPhone%>]

        }, {
            name: 'iPad',
            data: [<%=@dnloads_iPad%>, <%=@sessions_iPad%>]

        }, {
            name: 'Android',
            data: [<%=@dnloads_Android%>, <%=@sessions_Android%>]

        }]
    });
});
		</script>
	<link href="css/main.css" media="screen" rel="stylesheet" type="text/css" />		
	</head>
	<body>
		<script src="js/highcharts.js"></script>
		<script src="js/modules/exporting.js"></script>
		<div id="page_wrapper">
			<h2>Analytics on demand</h2>
			<div class="box">
				<p>Please enter the timeframe</p>
				<form action="/form" method="post">
				  
				  <label for="analytics_from">from:</label>
				  <input id="analytics_from" name="analytics_from" value="<%=@@analytics_from%>" type="date" required ="true" min="2014-01-01" max="<%= Time.now.strftime("%Y-%m-%d")%>">

				  <label for="analytics_to">to:</label>
				  <input id="analytics_to" name="analytics_to" value="<%=@@analytics_to%>" type="date" required="true" min="2014-01-01" max="<%= Time.now.strftime("%Y-%m-%d")%>">

				  <br/>
				  <input type="submit">
				</form>
				<% if !@dnloads_iPad.nil? %>
					<p class="box_summary">Total:<br />
					Downloads: <%= (@dnloads_iPhone+@dnloads_iPad+@dnloads_Android)%><br />
					Sessions: <%= (@sessions_iPhone+@sessions_iPad+@sessions_Android)%><br />
					<a class="btn" href="/form/download?analytics_from=<%=@@analytics_from%>&analytics_to=<%=@@analytics_to%>">download csv's</a>
					</p>
				<% end %>
			</div>
			<% if !@dnloads_iPad.nil? %>
				<div id="container" class="box" style="width: 400px; height: 400px; "></div>
			<% end %>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Analyticstool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/_form.erb
<%= form_for @tool do |f| %>
    <% if @tool.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tool.errors.count, "error") %>Tool konnte nicht gespeichert werden
            aus folgenden Gründen:</h2>
          <ul><% @tool.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %></ul>
        </div>
    <% end %>



    <p>
      <%= f.label :Toolname %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.submit %>
    </p>


<% end %>

app/views/tools/edit.erb
<h1>Ein Tool bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<h1>Alle Tools im Überblick</h1>

<p><%= link_to 'New tool', new_tool_path %></p>
<table>
  <tr>
    <th>Title</th>
    <!-- <th>Text</th> -->
  </tr>
 
  <% @tools.each do |tool| %>
    <tr >
      <td><%= tool.title %></td>
      <td><%= link_to 'Zeigen', tool_path(tool) %></td>
      <td><%= link_to 'Bearbeiten', edit_tool_path(tool) %></td>
      <td><%= link_to 'Löschen', tool_path(tool),
                      method: :delete, data: { confirm: 'Bist du sicher?' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Startseite', controller: 'welcome' %></p>

app/views/tools/new.html.erb
<h1>Hier können neue Tools hinzugefügt werden.</h1>

<%= render 'form' %>

<%= link_to 'Startseite', controller: 'welcome' %>

app/views/tools/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tool.title %>
</p>

<h2>Kommentare</h2>
<%= render @tool.comments %>


<h2>Füge ein Kommentar hinzu:</h2>
<%= render "comments/form" %>

<%= link_to 'Zurück', tools_path %>
| <%= link_to 'Bearbeiten', edit_tool_path(@tool) %>

app/views/welcome/index.html.erb
<h1>Willkommen zum Analysebereich</h1>
<br>
  
  <Table>
    <tr>
      <th>Was möchten sie tun ?</th>      
    </tr>
    <tr>
      <td><p><%= link_to 'Vorhandene Tools listen', controller: 'tools' %></p></td>
    </tr>
    <tr>      
      <td><p><%= link_to 'Neues Tool hinzufügen(DEV)', new_tool_path %></p></td>
    </tr>
    <tr>
      <td><p><%= link_to 'Bisherige Analysen anzeigen', controller: 'analytics' %></p></td>
    </tr>
    <tr>
      <td><p><%= link_to 'Analyse durchführen', new_analytic_path %></p></td>
    </tr>

  </Table>